### ISSUE TITLE
Add portfolio

### ISSUE THREAD

**Issue by aaronczichon** [aaronczichon/website#41]
# Description

My website is currently missing a portfolio. So I need to create a design and the data for a portfolio of things I've done in the last months and years.

# Tasks

- [] Collection projects which I want to show
- [ ] Create reference images of projects
- [ ] Create a design of what and how I want to show it
- [ ] Implement it into the website
